version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: supplyai-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: supplyai
      MYSQL_USER: supplyai
      MYSQL_PASSWORD: supplyai123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - supplyai-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: supplyai-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - supplyai-network
    command: start-dev

volumes:
  mysql_data:

networks:
  supplyai-network:
    driver: bridge
