# Profile específico para generación de OpenAPI
spring:
  profiles:
    active: openapi

# Configuración de SpringDoc para generación de especificación
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# Configuración de la aplicación
server:
  port: 8080

# Logging para OpenAPI
logging:
  level:
    org.springdoc: DEBUG
    com.supplyai: DEBUG
