name: Dependabot Auto-merge

# Dependabot workflow disabled temporarily
# on:
#   pull_request:
#     types: [opened, synchronize]
on:
  workflow_dispatch:  # Only manual execution

jobs:
  auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
    - name: Enable auto-merge for Dependabot PRs
      run: |
        gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
